In [1]:
from PattRecClasses import GaussD, HMM, MarkovChain
import numpy as np

#Test Forward algorithm FINITE CHAIN
finiteDurationMC = MarkovChain(np.array([1, 0]), np.array([[0.9, 0.1, 0], [0, 0.9, 0.1]])) 

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2
finiteDurationHMM  = HMM(finiteDurationMC, [g1, g2]) 
observations = np.array([-0.2, 2.6, 1.3])
scaledProbOfObservations = finiteDurationHMM.prob(observations, True)
alpha, c = finiteDurationMC.forward(scaledProbOfObservations)
print("Values for finite duration HMM:")
print("alfaHat:")
print(np.around(alpha, 4))
print("c: ")
print(np.around(c, 4))

Values for finite duration HMM:
alfaHat:
[[1.     0.3847 0.4189]
 [0.     0.6153 0.5811]]
c: 
[1.     0.1625 0.8266 0.0581]


In [2]:
#Test Forward algorithm NON-FINITE CHAIN
nonfiniteDurationMC = MarkovChain( np.array([1, 0]), np.array([[0.9, 0.1], [0.1, 0.9]])) 
nonfiniteDurationHMM  = HMM(nonfiniteDurationMC, [g1, g2]) 
scaledProbOfObservations = nonfiniteDurationHMM.prob(observations, True)
alpha, c = nonfiniteDurationMC.forward(scaledProbOfObservations)
print("Values for infinite duration HMM:")
print("alfaHat:")
print(np.around(alpha, 4))
print("c: ")
print(np.around(c, 4))

Values for infinite duration HMM:
alfaHat:
[[1.     0.3847 0.4591]
 [0.     0.6153 0.5409]]
c: 
[1.     0.1625 0.8881]


In [3]:
#Test logprob
logprob = finiteDurationHMM.logprob(observations)
print("logprob: ", logprob)

logprob:  -9.187726979475208
